name: Rust

on:
  push:
  pull_request:
  schedule:
    - cron: 5 16 * * 3



jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain: ["stable", "beta", "nightly"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install toolchains
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
    
    - name: Build
      run: cargo +${{ matrix.toolchain }} build --workspace --verbose
    - name: Run tests
      run: cargo +${{ matrix.toolchain }} test --workspace --all-features --verbose -- --skip _runsinglethread
    - name: Run tests (single-threaded tests)
      run: cargo +${{ matrix.toolchain }} test --workspace --all-features --verbose -- _runsinglethread --test-threads 1

    - name: Build docs (all features)
      run: cargo +${{ matrix.toolchain }} doc --workspace --all-features

    - name: Build docs
      run: cargo +${{ matrix.toolchain }} doc --workspace


  check:
    strategy:
      fail-fast: false
      matrix:
        toolchain: ["stable", "beta", "nightly"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchains (aarch64)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: aarch64-linux-android
      - name: Install toolchains (i686)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: i686-unknown-linux-gnu

      - name: cargo check (aarch64)
        run: cargo +${{ matrix.toolchain }} check --workspace --target aarch64-linux-android --all-features
      - name: cargo check (i686)
        run: cargo +${{ matrix.toolchain }} check --workspace --target i686-unknown-linux-gnu --all-features

